baseURL = 'https://andyzhu716.github.io/elecpower-blog/'
languageCode = 'zh-CN'
title = '电力设备选型指南'
theme = 'hugo-geekdoc'

[params]
  geekdocLogo = ''
  geekdocNav = true
  geekdocSearch = true
  geekdocRepo = ''
  geekdocEditPath = ''

[author]
  name = '朱帅'
  email = 'andyzhu716@gmail.com'
